language: node_js
node_js:
- '8'

script:
- npm run build

before_deploy:
# update package versions
- npm version "${TRAVIS_TAG}" --no-git-tag-version --save
- if [[ "${TRAVIS_TAG}" == *"beta"* ]]; then export NPM_TAG="next"; else export NPM_TAG="latest"; fi

deploy:
  provider: npm
  tag: "${NPM_TAG}"
  skip_cleanup: true
  email: igniteui@infragistics.com
  api_key:
    secure: mj+EoxRI9/kw5UcCg56CzdU4uSj3Bzn5KipgfC1LU1kehS55sBtnFBD1YhGc9qHdB/HM+qiKsOyhUNF6s1pTh8lvUOsu45VUHxAL/WQG/tZDu2UyO1+UYNLV3JkOddp8AVWH4oc/pO6pZxxXYn+Lhk+OWWOr5rD+2VJAKC1yJZ5j9j9IbX1wSwYMVo5MNwsZCUVuqRQqVfY4m6e56Nly4bx7PpN58HQyaSk86ElDAmPlMhT+pp879NdY+d4e1rUY6JNrZrnVXpDklCUo0L+/Tbz+ECIyVDtPcgiPRjAmi9EQj+ttoiF1QoonagyYGKb5JJQKq0pfgvEG73YdI9+mf3RxOIZ1P2S6nnxoH5UUmJExcG6xVT+ovfKDAyUvn9FxHN7XwZ4wwt6l4GcIOTJwy5zYQdlcD7miEaTAgh6ghNoTT92WllKzoyd5Zuhemg5yy6UkO3kAqLuUKmY6Z9DIOd1IUruNa+rue9m0iHkmp9Dl1v3NRrSnpf3K6cxhhOEHIZFy5FCKgE6Tu2A/dRdyQ0e6flDMiKIHAfKXNeTYmhHaDsgULM1bpIbCGiWz824Sajk2nEFY1WYIbI3fyQQ9PRL6tzxT4TrzvlGOfDB6sn11/rR68KTP/KQTRn6XzvOBSuiTaZ5KsmRMEATaqau0JNApqoiDB2E4h6hWFzn0jOc=
  on:
    tags: true
    repo: IgniteUI/sassdoc-plugin-localization
    branch: master
